name: CI/CD
on: [push]
jobs:
  Test:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The repository has been cloned to the runner."
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Build and run tests 🧪
        run: |
          docker build -t nycmesh-querybot-test .
          docker run --rm nycmesh-querybot-test pytest
  Deploy:
    runs-on: [self-hosted, daniel-server]
    env: 
      SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
    needs: [Test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build image
        run: docker build . -t nycmesh-querybot
      - name: Stop old container and run
        run: | 
          docker stop nycmesh-querybot || true
          docker rm nycmesh-querybot || true
          docker run -d --name nycmesh-querybot -p 4055:4055 -e SLACK_USER_TOKEN=$SLACK_USER_TOKEN nycmesh-querybot
      - name: Print startup output
        run: |
          sleep 5
          docker logs nycmesh-querybot
